# Generated by Django 3.0.3 on 2020-12-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=100)),
                ('book_serial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('book_image', models.ImageField(upload_to='media/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('review_stars_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=200)),
                ('publication', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('no_of_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('contact_number', models.IntegerField(default=0, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bought_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_by', to='apis.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to='apis.User'),
        ),
    ]
